[[data.Ray.level]]
level_id = "1A"
level_iid = "f104aa20-1030-11f0-8c81-53488ea5a5fd"
level_index = 15
complete = false
locked = false

[[data.Ray.level]]
level_id = "1B"
level_iid = "c20689f0-e920-11ef-a386-a5912fe41b56"
level_index = 8
complete = false
locked = true

[[data.Ray.level]]
level_id = "2#"
level_iid = "3415d600-e920-11ef-bc10-dd5aae6c2b26"
level_index = 11
complete = false
locked = true

[[data.Ray.level]]
level_id = "2A"
level_iid = "14c704f0-c210-11ef-833b-5533c9bd8e92"
level_index = 3
complete = false
locked = true

[[data.Ray.level]]
level_id = "2B"
level_iid = "4778a020-e920-11ef-bce6-e94bc30a0bcb"
level_index = 4
complete = false
locked = true

[[data.Ray.level]]
level_id = "2C"
level_iid = "a2b563a0-66b0-11ec-9cd7-fd8a9b24800f"
level_index = 0
complete = false
locked = true

[[data.Ray.level]]
level_id = "2D"
level_iid = "1b7bae30-e920-11ef-bce6-ab6ea8a9af2b"
level_index = 5
complete = false
locked = true

[[data.Ray.level]]
level_id = "2E"
level_iid = "c6195a90-e920-11ef-bce6-8fc247f83d86"
level_index = 6
complete = false
locked = true

[[data.Ray.level]]
level_id = "2F"
level_iid = "4bb54d80-e920-11ef-bce6-2bbf53423a3c"
level_index = 7
complete = false
locked = true

[[data.Ray.level]]
level_id = "2G"
level_iid = "8719ee90-e920-11ef-8222-114ef7b30846"
level_index = 10
complete = false
locked = true

[[data.Ray.level]]
level_id = "3#"
level_iid = "2c061e40-e920-11ef-bc10-6592ce07d1c8"
level_index = 12
complete = false
locked = true

[[data.Ray.level]]
level_id = "3A"
level_iid = "bbc5a580-c210-11ef-833b-1964d91f81b2"
level_index = 1
complete = false
locked = true

[[data.Ray.level]]
level_id = "3B"
level_iid = "4bcf44f0-c210-11ef-833b-4d843ec3db62"
level_index = 2
complete = false
locked = true

[[data.Ray.level]]
level_id = "4#"
level_iid = "460d2c70-e920-11ef-bc10-ad425a907c7b"
level_index = 13
complete = false
locked = true

[[data.Ray.level]]
level_id = "4A"
level_iid = "40948230-e920-11ef-8806-f7a59fa4fd04"
level_index = 9
complete = false
locked = true

[data.Ray.light]
unlocked = ["Green"]

[data.Ray.timer.timer]
is_paused = false

[data.Ray.timer.timer.elapsed]
secs = 5
nanos = 556902407

[[data.Test.level]]
level_id = "1A"
level_iid = "f104aa20-1030-11f0-8c81-53488ea5a5fd"
level_index = 15
complete = true
locked = false

[[data.Test.level]]
level_id = "1B"
level_iid = "c20689f0-e920-11ef-a386-a5912fe41b56"
level_index = 8
complete = false
locked = false

[[data.Test.level]]
level_id = "2#"
level_iid = "3415d600-e920-11ef-bc10-dd5aae6c2b26"
level_index = 11
complete = false
locked = true

[[data.Test.level]]
level_id = "2A"
level_iid = "14c704f0-c210-11ef-833b-5533c9bd8e92"
level_index = 3
complete = false
locked = true

[[data.Test.level]]
level_id = "2B"
level_iid = "4778a020-e920-11ef-bce6-e94bc30a0bcb"
level_index = 4
complete = false
locked = true

[[data.Test.level]]
level_id = "2C"
level_iid = "a2b563a0-66b0-11ec-9cd7-fd8a9b24800f"
level_index = 0
complete = false
locked = true

[[data.Test.level]]
level_id = "2D"
level_iid = "1b7bae30-e920-11ef-bce6-ab6ea8a9af2b"
level_index = 5
complete = false
locked = true

[[data.Test.level]]
level_id = "2E"
level_iid = "c6195a90-e920-11ef-bce6-8fc247f83d86"
level_index = 6
complete = false
locked = true

[[data.Test.level]]
level_id = "2F"
level_iid = "4bb54d80-e920-11ef-bce6-2bbf53423a3c"
level_index = 7
complete = false
locked = true

[[data.Test.level]]
level_id = "2G"
level_iid = "8719ee90-e920-11ef-8222-114ef7b30846"
level_index = 10
complete = false
locked = true

[[data.Test.level]]
level_id = "3#"
level_iid = "2c061e40-e920-11ef-bc10-6592ce07d1c8"
level_index = 12
complete = false
locked = true

[[data.Test.level]]
level_id = "3A"
level_iid = "bbc5a580-c210-11ef-833b-1964d91f81b2"
level_index = 1
complete = false
locked = true

[[data.Test.level]]
level_id = "3B"
level_iid = "4bcf44f0-c210-11ef-833b-4d843ec3db62"
level_index = 2
complete = false
locked = true

[[data.Test.level]]
level_id = "4#"
level_iid = "460d2c70-e920-11ef-bc10-ad425a907c7b"
level_index = 13
complete = false
locked = true

[[data.Test.level]]
level_id = "4A"
level_iid = "40948230-e920-11ef-8806-f7a59fa4fd04"
level_index = 9
complete = false
locked = true

[data.Test.light]
unlocked = ["Green"]

[data.Test.timer.timer]
is_paused = false

[data.Test.timer.timer.elapsed]
secs = 18
nanos = 811012412

[[data.NewHi.level]]
level_id = "1A"
level_iid = "f104aa20-1030-11f0-8c81-53488ea5a5fd"
level_index = 15
complete = true
locked = false

[[data.NewHi.level]]
level_id = "1B"
level_iid = "c20689f0-e920-11ef-a386-a5912fe41b56"
level_index = 8
complete = true
locked = false

[[data.NewHi.level]]
level_id = "2#"
level_iid = "3415d600-e920-11ef-bc10-dd5aae6c2b26"
level_index = 11
complete = false
locked = false

[[data.NewHi.level]]
level_id = "2A"
level_iid = "14c704f0-c210-11ef-833b-5533c9bd8e92"
level_index = 3
complete = false
locked = true

[[data.NewHi.level]]
level_id = "2B"
level_iid = "4778a020-e920-11ef-bce6-e94bc30a0bcb"
level_index = 4
complete = false
locked = true

[[data.NewHi.level]]
level_id = "2C"
level_iid = "a2b563a0-66b0-11ec-9cd7-fd8a9b24800f"
level_index = 0
complete = false
locked = true

[[data.NewHi.level]]
level_id = "2D"
level_iid = "1b7bae30-e920-11ef-bce6-ab6ea8a9af2b"
level_index = 5
complete = false
locked = true

[[data.NewHi.level]]
level_id = "2E"
level_iid = "c6195a90-e920-11ef-bce6-8fc247f83d86"
level_index = 6
complete = false
locked = true

[[data.NewHi.level]]
level_id = "2F"
level_iid = "4bb54d80-e920-11ef-bce6-2bbf53423a3c"
level_index = 7
complete = false
locked = true

[[data.NewHi.level]]
level_id = "2G"
level_iid = "8719ee90-e920-11ef-8222-114ef7b30846"
level_index = 10
complete = false
locked = true

[[data.NewHi.level]]
level_id = "3#"
level_iid = "2c061e40-e920-11ef-bc10-6592ce07d1c8"
level_index = 12
complete = false
locked = true

[[data.NewHi.level]]
level_id = "3A"
level_iid = "bbc5a580-c210-11ef-833b-1964d91f81b2"
level_index = 1
complete = false
locked = true

[[data.NewHi.level]]
level_id = "3B"
level_iid = "4bcf44f0-c210-11ef-833b-4d843ec3db62"
level_index = 2
complete = false
locked = true

[[data.NewHi.level]]
level_id = "4#"
level_iid = "460d2c70-e920-11ef-bc10-ad425a907c7b"
level_index = 13
complete = false
locked = true

[[data.NewHi.level]]
level_id = "4A"
level_iid = "40948230-e920-11ef-8806-f7a59fa4fd04"
level_index = 9
complete = false
locked = true

[data.NewHi.light]
unlocked = ["Green"]

[data.NewHi.timer.timer]
is_paused = false

[data.NewHi.timer.timer.elapsed]
secs = 26
nanos = 27545420

[[data.dasdjasdasjdlksj.level]]
level_id = "1A"
level_iid = "f104aa20-1030-11f0-8c81-53488ea5a5fd"
level_index = 15
complete = true
locked = false

[[data.dasdjasdasjdlksj.level]]
level_id = "1B"
level_iid = "c20689f0-e920-11ef-a386-a5912fe41b56"
level_index = 8
complete = false
locked = false

[[data.dasdjasdasjdlksj.level]]
level_id = "2#"
level_iid = "3415d600-e920-11ef-bc10-dd5aae6c2b26"
level_index = 11
complete = false
locked = true

[[data.dasdjasdasjdlksj.level]]
level_id = "2A"
level_iid = "14c704f0-c210-11ef-833b-5533c9bd8e92"
level_index = 3
complete = false
locked = true

[[data.dasdjasdasjdlksj.level]]
level_id = "2B"
level_iid = "4778a020-e920-11ef-bce6-e94bc30a0bcb"
level_index = 4
complete = false
locked = true

[[data.dasdjasdasjdlksj.level]]
level_id = "2C"
level_iid = "a2b563a0-66b0-11ec-9cd7-fd8a9b24800f"
level_index = 0
complete = false
locked = true

[[data.dasdjasdasjdlksj.level]]
level_id = "2D"
level_iid = "1b7bae30-e920-11ef-bce6-ab6ea8a9af2b"
level_index = 5
complete = false
locked = true

[[data.dasdjasdasjdlksj.level]]
level_id = "2E"
level_iid = "c6195a90-e920-11ef-bce6-8fc247f83d86"
level_index = 6
complete = false
locked = true

[[data.dasdjasdasjdlksj.level]]
level_id = "2F"
level_iid = "4bb54d80-e920-11ef-bce6-2bbf53423a3c"
level_index = 7
complete = false
locked = true

[[data.dasdjasdasjdlksj.level]]
level_id = "2G"
level_iid = "8719ee90-e920-11ef-8222-114ef7b30846"
level_index = 10
complete = false
locked = true

[[data.dasdjasdasjdlksj.level]]
level_id = "3#"
level_iid = "2c061e40-e920-11ef-bc10-6592ce07d1c8"
level_index = 12
complete = false
locked = true

[[data.dasdjasdasjdlksj.level]]
level_id = "3A"
level_iid = "bbc5a580-c210-11ef-833b-1964d91f81b2"
level_index = 1
complete = false
locked = true

[[data.dasdjasdasjdlksj.level]]
level_id = "3B"
level_iid = "4bcf44f0-c210-11ef-833b-4d843ec3db62"
level_index = 2
complete = false
locked = true

[[data.dasdjasdasjdlksj.level]]
level_id = "4#"
level_iid = "460d2c70-e920-11ef-bc10-ad425a907c7b"
level_index = 13
complete = false
locked = true

[[data.dasdjasdasjdlksj.level]]
level_id = "4A"
level_iid = "40948230-e920-11ef-8806-f7a59fa4fd04"
level_index = 9
complete = false
locked = true

[data.dasdjasdasjdlksj.light]
unlocked = ["Green"]

[data.dasdjasdasjdlksj.timer.timer]
is_paused = false

[data.dasdjasdasjdlksj.timer.timer.elapsed]
secs = 9
nanos = 454586598

[[data.ra.level]]
level_id = "1A"
level_iid = "f104aa20-1030-11f0-8c81-53488ea5a5fd"
level_index = 15
complete = false
locked = false

[[data.ra.level]]
level_id = "1B"
level_iid = "c20689f0-e920-11ef-a386-a5912fe41b56"
level_index = 8
complete = false
locked = true

[[data.ra.level]]
level_id = "2#"
level_iid = "3415d600-e920-11ef-bc10-dd5aae6c2b26"
level_index = 11
complete = false
locked = true

[[data.ra.level]]
level_id = "2A"
level_iid = "14c704f0-c210-11ef-833b-5533c9bd8e92"
level_index = 3
complete = false
locked = true

[[data.ra.level]]
level_id = "2B"
level_iid = "4778a020-e920-11ef-bce6-e94bc30a0bcb"
level_index = 4
complete = false
locked = true

[[data.ra.level]]
level_id = "2C"
level_iid = "a2b563a0-66b0-11ec-9cd7-fd8a9b24800f"
level_index = 0
complete = false
locked = true

[[data.ra.level]]
level_id = "2D"
level_iid = "1b7bae30-e920-11ef-bce6-ab6ea8a9af2b"
level_index = 5
complete = false
locked = true

[[data.ra.level]]
level_id = "2E"
level_iid = "c6195a90-e920-11ef-bce6-8fc247f83d86"
level_index = 6
complete = false
locked = true

[[data.ra.level]]
level_id = "2F"
level_iid = "4bb54d80-e920-11ef-bce6-2bbf53423a3c"
level_index = 7
complete = false
locked = true

[[data.ra.level]]
level_id = "2G"
level_iid = "8719ee90-e920-11ef-8222-114ef7b30846"
level_index = 10
complete = false
locked = true

[[data.ra.level]]
level_id = "3#"
level_iid = "2c061e40-e920-11ef-bc10-6592ce07d1c8"
level_index = 12
complete = false
locked = true

[[data.ra.level]]
level_id = "3A"
level_iid = "bbc5a580-c210-11ef-833b-1964d91f81b2"
level_index = 1
complete = false
locked = true

[[data.ra.level]]
level_id = "3B"
level_iid = "4bcf44f0-c210-11ef-833b-4d843ec3db62"
level_index = 2
complete = false
locked = true

[[data.ra.level]]
level_id = "4#"
level_iid = "460d2c70-e920-11ef-bc10-ad425a907c7b"
level_index = 13
complete = false
locked = true

[[data.ra.level]]
level_id = "4A"
level_iid = "40948230-e920-11ef-8806-f7a59fa4fd04"
level_index = 9
complete = false
locked = true

[data.ra.light]
unlocked = []

[data.ra.timer.timer]
is_paused = false

[data.ra.timer.timer.elapsed]
secs = 0
nanos = 545792559

[[data.dsa.level]]
level_id = "1A"
level_iid = "f104aa20-1030-11f0-8c81-53488ea5a5fd"
level_index = 15
complete = false
locked = false

[[data.dsa.level]]
level_id = "1B"
level_iid = "c20689f0-e920-11ef-a386-a5912fe41b56"
level_index = 8
complete = false
locked = true

[[data.dsa.level]]
level_id = "2#"
level_iid = "3415d600-e920-11ef-bc10-dd5aae6c2b26"
level_index = 11
complete = false
locked = true

[[data.dsa.level]]
level_id = "2A"
level_iid = "14c704f0-c210-11ef-833b-5533c9bd8e92"
level_index = 3
complete = false
locked = true

[[data.dsa.level]]
level_id = "2B"
level_iid = "4778a020-e920-11ef-bce6-e94bc30a0bcb"
level_index = 4
complete = false
locked = true

[[data.dsa.level]]
level_id = "2C"
level_iid = "a2b563a0-66b0-11ec-9cd7-fd8a9b24800f"
level_index = 0
complete = false
locked = true

[[data.dsa.level]]
level_id = "2D"
level_iid = "1b7bae30-e920-11ef-bce6-ab6ea8a9af2b"
level_index = 5
complete = false
locked = true

[[data.dsa.level]]
level_id = "2E"
level_iid = "c6195a90-e920-11ef-bce6-8fc247f83d86"
level_index = 6
complete = false
locked = true

[[data.dsa.level]]
level_id = "2F"
level_iid = "4bb54d80-e920-11ef-bce6-2bbf53423a3c"
level_index = 7
complete = false
locked = true

[[data.dsa.level]]
level_id = "2G"
level_iid = "8719ee90-e920-11ef-8222-114ef7b30846"
level_index = 10
complete = false
locked = true

[[data.dsa.level]]
level_id = "3#"
level_iid = "2c061e40-e920-11ef-bc10-6592ce07d1c8"
level_index = 12
complete = false
locked = true

[[data.dsa.level]]
level_id = "3A"
level_iid = "bbc5a580-c210-11ef-833b-1964d91f81b2"
level_index = 1
complete = false
locked = true

[[data.dsa.level]]
level_id = "3B"
level_iid = "4bcf44f0-c210-11ef-833b-4d843ec3db62"
level_index = 2
complete = false
locked = true

[[data.dsa.level]]
level_id = "4#"
level_iid = "460d2c70-e920-11ef-bc10-ad425a907c7b"
level_index = 13
complete = false
locked = true

[[data.dsa.level]]
level_id = "4A"
level_iid = "40948230-e920-11ef-8806-f7a59fa4fd04"
level_index = 9
complete = false
locked = true

[data.dsa.light]
unlocked = []

[data.dsa.timer.timer]
is_paused = false

[data.dsa.timer.timer.elapsed]
secs = 0
nanos = 716916918

[[data.Raymond.level]]
level_id = "1A"
level_iid = "f104aa20-1030-11f0-8c81-53488ea5a5fd"
level_index = 15
complete = true
locked = false

[[data.Raymond.level]]
level_id = "1B"
level_iid = "c20689f0-e920-11ef-a386-a5912fe41b56"
level_index = 8
complete = true
locked = false

[[data.Raymond.level]]
level_id = "2#"
level_iid = "3415d600-e920-11ef-bc10-dd5aae6c2b26"
level_index = 11
complete = true
locked = false

[[data.Raymond.level]]
level_id = "2A"
level_iid = "14c704f0-c210-11ef-833b-5533c9bd8e92"
level_index = 3
complete = true
locked = false

[[data.Raymond.level]]
level_id = "2B"
level_iid = "4778a020-e920-11ef-bce6-e94bc30a0bcb"
level_index = 4
complete = true
locked = false

[[data.Raymond.level]]
level_id = "2C"
level_iid = "a2b563a0-66b0-11ec-9cd7-fd8a9b24800f"
level_index = 0
complete = true
locked = false

[[data.Raymond.level]]
level_id = "2D"
level_iid = "1b7bae30-e920-11ef-bce6-ab6ea8a9af2b"
level_index = 5
complete = true
locked = false

[[data.Raymond.level]]
level_id = "2E"
level_iid = "c6195a90-e920-11ef-bce6-8fc247f83d86"
level_index = 6
complete = true
locked = false

[[data.Raymond.level]]
level_id = "2F"
level_iid = "4bb54d80-e920-11ef-bce6-2bbf53423a3c"
level_index = 7
complete = true
locked = false

[[data.Raymond.level]]
level_id = "2G"
level_iid = "8719ee90-e920-11ef-8222-114ef7b30846"
level_index = 10
complete = true
locked = false

[[data.Raymond.level]]
level_id = "3#"
level_iid = "2c061e40-e920-11ef-bc10-6592ce07d1c8"
level_index = 12
complete = true
locked = false

[[data.Raymond.level]]
level_id = "3A"
level_iid = "bbc5a580-c210-11ef-833b-1964d91f81b2"
level_index = 1
complete = true
locked = false

[[data.Raymond.level]]
level_id = "3B"
level_iid = "4bcf44f0-c210-11ef-833b-4d843ec3db62"
level_index = 2
complete = true
locked = false

[[data.Raymond.level]]
level_id = "4#"
level_iid = "460d2c70-e920-11ef-bc10-ad425a907c7b"
level_index = 13
complete = true
locked = false

[[data.Raymond.level]]
level_id = "4A"
level_iid = "40948230-e920-11ef-8806-f7a59fa4fd04"
level_index = 9
complete = false
locked = false

[data.Raymond.light]
unlocked = [
    "Green",
    "Purple",
    "White",
    "Blue",
]

[data.Raymond.timer.timer]
is_paused = false

[data.Raymond.timer.timer.elapsed]
secs = 212
nanos = 892559976

[[data.New.level]]
level_id = "1A"
level_iid = "f104aa20-1030-11f0-8c81-53488ea5a5fd"
level_index = 15
complete = false
locked = false

[[data.New.level]]
level_id = "1B"
level_iid = "c20689f0-e920-11ef-a386-a5912fe41b56"
level_index = 8
complete = false
locked = true

[[data.New.level]]
level_id = "2#"
level_iid = "3415d600-e920-11ef-bc10-dd5aae6c2b26"
level_index = 11
complete = false
locked = true

[[data.New.level]]
level_id = "2A"
level_iid = "14c704f0-c210-11ef-833b-5533c9bd8e92"
level_index = 3
complete = false
locked = true

[[data.New.level]]
level_id = "2B"
level_iid = "4778a020-e920-11ef-bce6-e94bc30a0bcb"
level_index = 4
complete = false
locked = true

[[data.New.level]]
level_id = "2C"
level_iid = "a2b563a0-66b0-11ec-9cd7-fd8a9b24800f"
level_index = 0
complete = false
locked = true

[[data.New.level]]
level_id = "2D"
level_iid = "1b7bae30-e920-11ef-bce6-ab6ea8a9af2b"
level_index = 5
complete = false
locked = true

[[data.New.level]]
level_id = "2E"
level_iid = "c6195a90-e920-11ef-bce6-8fc247f83d86"
level_index = 6
complete = false
locked = true

[[data.New.level]]
level_id = "2F"
level_iid = "4bb54d80-e920-11ef-bce6-2bbf53423a3c"
level_index = 7
complete = false
locked = true

[[data.New.level]]
level_id = "2G"
level_iid = "8719ee90-e920-11ef-8222-114ef7b30846"
level_index = 10
complete = false
locked = true

[[data.New.level]]
level_id = "3#"
level_iid = "2c061e40-e920-11ef-bc10-6592ce07d1c8"
level_index = 12
complete = false
locked = true

[[data.New.level]]
level_id = "3A"
level_iid = "bbc5a580-c210-11ef-833b-1964d91f81b2"
level_index = 1
complete = false
locked = true

[[data.New.level]]
level_id = "3B"
level_iid = "4bcf44f0-c210-11ef-833b-4d843ec3db62"
level_index = 2
complete = false
locked = true

[[data.New.level]]
level_id = "4#"
level_iid = "460d2c70-e920-11ef-bc10-ad425a907c7b"
level_index = 13
complete = false
locked = true

[[data.New.level]]
level_id = "4A"
level_iid = "40948230-e920-11ef-8806-f7a59fa4fd04"
level_index = 9
complete = false
locked = true

[data.New.light]
unlocked = ["Green"]

[data.New.timer.timer]
is_paused = false

[data.New.timer.timer.elapsed]
secs = 3
nanos = 824743218

[[data.raraa.level]]
level_id = "1A"
level_iid = "f104aa20-1030-11f0-8c81-53488ea5a5fd"
level_index = 15
complete = false
locked = false

[[data.raraa.level]]
level_id = "1B"
level_iid = "c20689f0-e920-11ef-a386-a5912fe41b56"
level_index = 8
complete = false
locked = true

[[data.raraa.level]]
level_id = "2#"
level_iid = "3415d600-e920-11ef-bc10-dd5aae6c2b26"
level_index = 11
complete = false
locked = true

[[data.raraa.level]]
level_id = "2A"
level_iid = "14c704f0-c210-11ef-833b-5533c9bd8e92"
level_index = 3
complete = false
locked = true

[[data.raraa.level]]
level_id = "2B"
level_iid = "4778a020-e920-11ef-bce6-e94bc30a0bcb"
level_index = 4
complete = false
locked = true

[[data.raraa.level]]
level_id = "2C"
level_iid = "a2b563a0-66b0-11ec-9cd7-fd8a9b24800f"
level_index = 0
complete = false
locked = true

[[data.raraa.level]]
level_id = "2D"
level_iid = "1b7bae30-e920-11ef-bce6-ab6ea8a9af2b"
level_index = 5
complete = false
locked = true

[[data.raraa.level]]
level_id = "2E"
level_iid = "c6195a90-e920-11ef-bce6-8fc247f83d86"
level_index = 6
complete = false
locked = true

[[data.raraa.level]]
level_id = "2F"
level_iid = "4bb54d80-e920-11ef-bce6-2bbf53423a3c"
level_index = 7
complete = false
locked = true

[[data.raraa.level]]
level_id = "2G"
level_iid = "8719ee90-e920-11ef-8222-114ef7b30846"
level_index = 10
complete = false
locked = true

[[data.raraa.level]]
level_id = "3#"
level_iid = "2c061e40-e920-11ef-bc10-6592ce07d1c8"
level_index = 12
complete = false
locked = true

[[data.raraa.level]]
level_id = "3A"
level_iid = "bbc5a580-c210-11ef-833b-1964d91f81b2"
level_index = 1
complete = false
locked = true

[[data.raraa.level]]
level_id = "3B"
level_iid = "4bcf44f0-c210-11ef-833b-4d843ec3db62"
level_index = 2
complete = false
locked = true

[[data.raraa.level]]
level_id = "4#"
level_iid = "460d2c70-e920-11ef-bc10-ad425a907c7b"
level_index = 13
complete = false
locked = true

[[data.raraa.level]]
level_id = "4A"
level_iid = "40948230-e920-11ef-8806-f7a59fa4fd04"
level_index = 9
complete = false
locked = true

[data.raraa.light]
unlocked = []

[data.raraa.timer.timer]
is_paused = false

[data.raraa.timer.timer.elapsed]
secs = 0
nanos = 304942803
